# TODO 配置数据源相关信息

server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/web_user?serverTimezone=UTC&rewriteBatchedStatements = true
    username: root
    password: 1234
mybatis-plus:
  global-config:
    db-config:
      table-prefix: t_
      id-type: auto
      logic-delete-field: deleted
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
knife4j:
  enable: true
  setting:
    language: zh_cn